#! /bin/sh
### BEGIN INIT INFO
# Provides:          Prime Server
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Prime-Server webservice
# Description:       Starts web service that determines whether a number is prime.
#
### END INIT INFO

# Author: Bjoern Lohrmann <bjoern.lohrmann@tu-berlin.de>
#

# Do NOT "set -e"

#set -x

# PATH should only include /usr/* if it runs after the mountnfs.sh script
export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/var/lib/gems/1.8/bin
DESC="Prime-Server Webservice"
#NAME=daemonexecutablename
#DAEMON=/usr/sbin/$NAME
#DAEMON_ARGS="--options args"
SCRIPTNAME=/etc/init.d/primeserver

# Read configuration variable file if it is present
#[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
        # Return
        #   0 if daemon has been started
        #   1 if daemon was already running
        #   2 if daemon could not be started

        ( su -l primeserver -c "/home/primeserver/prime-service/prime-server.sh" )
	return "$?"
}

#
# Function that stops the daemon/service
#
do_stop()
{
        # Return
        #   0 if daemon has been stopped
        #   1 if daemon was already stopped
        #   2 if daemon could not be stopped
        #   other if a failure occurred
        killall -u primeserver java
        return "$?"
}

#
# Function that restarts the daemon/service
#
do_restart()
{
        do_stop
	do_start
}

case "$1" in
  start)
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
        do_start
        case "$?" in
                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  stop)
        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop
        case "$?" in
                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  restart)
        log_daemon_msg "Restarting $DESC" "$NAME"
        do_restart
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
        exit 3
        ;;
esac

:
