package de.tu_berlin.cit.prime.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-15T22:22:31.648+02:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://server.prime.cit.tu_berlin.de/", name = "PrimeServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface PrimeServicePortType {

    @WebResult(name = "return", targetNamespace = "http://server.prime.cit.tu_berlin.de/")
    @RequestWrapper(localName = "isPrime", targetNamespace = "http://server.prime.cit.tu_berlin.de/", className = "de.tu_berlin.cit.prime.client.IsPrime")
    @WebMethod
    @ResponseWrapper(localName = "isPrimeResponse", targetNamespace = "http://server.prime.cit.tu_berlin.de/", className = "de.tu_berlin.cit.prime.client.IsPrimeResponse")
    public boolean isPrime(
        @WebParam(name = "arg0", targetNamespace = "http://server.prime.cit.tu_berlin.de/")
        long arg0
    );
}
